-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 21:23:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `piso` VARCHAR(5) NULL,
  `puerta` VARCHAR(5) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `fax` INT NULL,
  `NIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`producto_gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`producto_gafas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion_derecha` INT NOT NULL,
  `graduacion_izquierda` INT NOT NULL,
  `tipo_montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_cristal` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `proveedor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedor_idx` (`proveedor` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `proveedor`
    FOREIGN KEY (`proveedor`)
    REFERENCES `optica`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `piso` VARCHAR(5) NOT NULL,
  `puerta` VARCHAR(5) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `recomendado_por` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `recomendado_por_idx` (`recomendado_por` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `recomendado_por`
    FOREIGN KEY (`recomendado_por`)
    REFERENCES `optica`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`empleados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `total_orden` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `optica`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `optica`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `producto_gafas_id` INT NOT NULL,
  INDEX `fk_order_has_producto_gafas_producto_gafas1_idx` (`producto_gafas_id` ASC) VISIBLE,
  INDEX `fk_order_has_producto_gafas_order1_idx` (`order_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_has_producto_gafas_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `optica`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_producto_gafas_producto_gafas1`
    FOREIGN KEY (`producto_gafas_id`)
    REFERENCES `optica`.`producto_gafas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ingreso datos de la tabla de proveedores
USE optica;
INSERT INTO proveedor (nombre, calle, numero, piso, puerta, ciudad, codigo_postal, pais, telefono, fax, NIF) VALUES 
("Gafa pasta", "Arago", 47, "1ro", "2", "Barcelona", 08015, "España", 934444444, 935555555, "B44444444"), 
("Anteojito", "Mirador", 8, "bajos", "local", "Napoles", 1324, "Italia", 345678910, 345678910, "FG1111111");

SELECT * FROM proveedor;

-- ingreso datos a la tabla de productos_gafas
USE optica;
INSERT INTO producto_gafas (marca, graduacion_derecha, graduacion_izquierda, tipo_montura, color_montura, color_cristal, precio, proveedor)
VALUES
("Rai Ban", 0, 0, "pasta", "negro", "negro", 140.00, 1),
("Oakley", 0, 0, "flotante", "dorado","marron", 130.45, 1),
("Polaroid", 1, 1, "metalica", "plata", "transparente", 152.35, 1),
("Carrera", 0, 0, "pasta", "rojo", "negro", 126.32, 2),
("Arnette", 0, 0, "metalica", "dorado", "azul", 130.88, 2),
("Tous", 2, 2, "pasta", "marrón", "negro", 144.00, 2);

SELECT * FROM producto_gafas;

-- ingreso los empleados
USE optica;
INSERT INTO empleados (id, nombre) VALUES (1,"Ana"), (2,"Pedro"), (3,"Rosa");
SELECT * FROM empleados;

-- ingreso clientes
USE optica;
INSERT INTO cliente (nombre, apellido, calle, numero, piso, puerta, ciudad, codigo_postal, pais, recomendado_por)
VALUES
("Jose", "Perez", "Diputacio", 27, "1ro", "2da", "Barcelona", 08000, "España", NULL ),
("Maria", "Garcia", "Arago", 33, "4to", "2da", "Barcelona", 08030, "España", NULL ),
("Paco", "Matti", "Girona", 47, "1ro", "5ta", "Barcelona", 08005, "España", NULL ),
("Clara", "Toledo", "Roma", 267, "1ro", "A", "Barcelona", 08000, "España", NULL ),
("Carmen", "Puig", "Diputacio", 77, "1ro", "2da", "Barcelona", 08000, "España", 1 ),
("Carlos", "Paz", "Llanca", 2, "6to", "2da", "Barcelona", 08000, "España", 2 );

SELECT * FROM cliente;
-- ingreso algunos pedidos para luego hacer las pruebas
USE optica;
INSERT INTO orden (fecha, id_cliente, id_empleado, total_orden)
VALUES ('2022-12-31 13:59:59', 3, 2, 900.00);
INSERT INTO order_detail (order_id, producto_gafas_id) VALUES (1, 2), (1,4), (1,5);

INSERT INTO orden (fecha, id_cliente, id_empleado, total_orden)
VALUES ('2022-10-28 11:59:59', 5, 1, 150.00);
INSERT INTO order_detail (order_id, producto_gafas_id) VALUES (2, 1);

INSERT INTO orden (fecha, id_cliente, id_empleado, total_orden)
VALUES ('2022-12-31 14:59:59', 1, 3, 400.00);
INSERT INTO order_detail (order_id, producto_gafas_id) VALUES (3, 6), (3,3);

INSERT INTO orden (fecha, id_cliente, id_empleado, total_orden)
VALUES ('2022-12-11 10:59:59', 3, 2, 950.00);
INSERT INTO order_detail (order_id, producto_gafas_id) VALUES (4, 6), (4,4), (4,1);

INSERT INTO orden (fecha, id_cliente, id_empleado, total_orden)
VALUES ('2022-12-11 10:59:59', 1, 1, 550.00);
INSERT INTO order_detail (order_id, producto_gafas_id) VALUES (5, 3), (5,1);

-- listar el total de ordenes de un cliente en un periodo determinado
SELECT * FROM orden
WHERE id_cliente = 1 AND fecha BETWEEN '2022-01-01' AND '2022-12-31';

-- consulta de gafas que ha vendido el empleado 2 en 2022
SELECT p.id, p.marca, p.precio
FROM producto_gafas p
JOIN (
  SELECT o.id, od.producto_gafas_id
  FROM orden o
  JOIN order_detail od ON o.id = od.order_id
  WHERE o.id_empleado = 2 AND YEAR(o.fecha) = 2022
) t ON p.id = t.producto_gafas_id;

-- listar los proveedores de los que de han vendido gafas
SELECT DISTINCT(pr.nombre)
FROM producto_gafas pg
JOIN proveedor pr ON pg.proveedor = pr.idproveedor
JOIN order_detail od ON pg.id = od.producto_gafas_id
JOIN orden o ON od.order_id = o.id
WHERE o.total_orden > 0;


